# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1058, 600)
        self.main = QtWidgets.QWidget(MainWindow)
        self.main.setObjectName("main")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main)
        self.stackedWidget.setGeometry(QtCore.QRect(-10, 0, 1071, 601))
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainpage = QtWidgets.QWidget()
        self.mainpage.setObjectName("mainpage")
        self.title = QtWidgets.QLabel(self.mainpage)
        self.title.setGeometry(QtCore.QRect(340, 120, 111, 20))
        self.title.setObjectName("title")
        self.rsabutton = QtWidgets.QPushButton(self.mainpage)
        self.rsabutton.setGeometry(QtCore.QRect(340, 170, 97, 33))
        self.rsabutton.setObjectName("rsabutton")
        self.egbutton = QtWidgets.QPushButton(self.mainpage)
        self.egbutton.setGeometry(QtCore.QRect(340, 220, 97, 33))
        self.egbutton.setObjectName("egbutton")
        self.stackedWidget.addWidget(self.mainpage)
        self.RSA = QtWidgets.QWidget()
        self.RSA.setObjectName("RSA")
        self.RSA_sess_n_value = QtWidgets.QLineEdit(self.RSA)
        self.RSA_sess_n_value.setGeometry(QtCore.QRect(240, 100, 113, 31))
        self.RSA_sess_n_value.setObjectName("RSA_sess_n_value")
        self.RSA_sess_y_value = QtWidgets.QLineEdit(self.RSA)
        self.RSA_sess_y_value.setGeometry(QtCore.QRect(240, 220, 113, 31))
        self.RSA_sess_y_value.setObjectName("RSA_sess_y_value")
        self.RSA_title = QtWidgets.QLabel(self.RSA)
        self.RSA_title.setGeometry(QtCore.QRect(530, 20, 67, 17))
        self.RSA_title.setObjectName("RSA_title")
        self.RSA_key_y_value = QtWidgets.QLineEdit(self.RSA)
        self.RSA_key_y_value.setGeometry(QtCore.QRect(70, 220, 113, 31))
        self.RSA_key_y_value.setObjectName("RSA_key_y_value")
        self.RSA_returnbutton = QtWidgets.QPushButton(self.RSA)
        self.RSA_returnbutton.setGeometry(QtCore.QRect(500, 530, 97, 33))
        self.RSA_returnbutton.setObjectName("RSA_returnbutton")
        self.RSA_sess_y_label = QtWidgets.QLabel(self.RSA)
        self.RSA_sess_y_label.setGeometry(QtCore.QRect(220, 220, 16, 17))
        self.RSA_sess_y_label.setObjectName("RSA_sess_y_label")
        self.RSA_sess_genbutton = QtWidgets.QPushButton(self.RSA)
        self.RSA_sess_genbutton.setGeometry(QtCore.QRect(220, 260, 151, 31))
        self.RSA_sess_genbutton.setObjectName("RSA_sess_genbutton")
        self.RSA_sess_label = QtWidgets.QLabel(self.RSA)
        self.RSA_sess_label.setGeometry(QtCore.QRect(220, 60, 151, 17))
        self.RSA_sess_label.setObjectName("RSA_sess_label")
        self.RSA_act_encbutton = QtWidgets.QRadioButton(self.RSA)
        self.RSA_act_encbutton.setGeometry(QtCore.QRect(520, 250, 115, 21))
        self.RSA_act_encbutton.setObjectName("RSA_act_encbutton")
        self.RSA_sess_x_label = QtWidgets.QLabel(self.RSA)
        self.RSA_sess_x_label.setGeometry(QtCore.QRect(220, 140, 16, 17))
        self.RSA_sess_x_label.setObjectName("RSA_sess_x_label")
        self.RSA_key_g_label = QtWidgets.QLabel(self.RSA)
        self.RSA_key_g_label.setGeometry(QtCore.QRect(50, 180, 16, 17))
        self.RSA_key_g_label.setObjectName("RSA_key_g_label")
        self.RSA_sess_n_label = QtWidgets.QLabel(self.RSA)
        self.RSA_sess_n_label.setGeometry(QtCore.QRect(220, 100, 16, 17))
        self.RSA_sess_n_label.setObjectName("RSA_sess_n_label")
        self.RSA_input_text = QtWidgets.QTextEdit(self.RSA)
        self.RSA_input_text.setGeometry(QtCore.QRect(520, 90, 511, 111))
        self.RSA_input_text.setObjectName("RSA_input_text")
        self.RSA_input_filebutton = QtWidgets.QPushButton(self.RSA)
        self.RSA_input_filebutton.setGeometry(QtCore.QRect(880, 210, 151, 33))
        self.RSA_input_filebutton.setObjectName("RSA_input_filebutton")
        self.RSA_key_y_label = QtWidgets.QLabel(self.RSA)
        self.RSA_key_y_label.setGeometry(QtCore.QRect(50, 220, 16, 17))
        self.RSA_key_y_label.setObjectName("RSA_key_y_label")
        self.RSA_key_label = QtWidgets.QLabel(self.RSA)
        self.RSA_key_label.setGeometry(QtCore.QRect(50, 60, 151, 17))
        self.RSA_key_label.setObjectName("RSA_key_label")
        self.RSA_key_g_value = QtWidgets.QLineEdit(self.RSA)
        self.RSA_key_g_value.setGeometry(QtCore.QRect(70, 180, 113, 31))
        self.RSA_key_g_value.setObjectName("RSA_key_g_value")
        self.RSA_key_p_value = QtWidgets.QLineEdit(self.RSA)
        self.RSA_key_p_value.setGeometry(QtCore.QRect(70, 100, 113, 31))
        self.RSA_key_p_value.setObjectName("RSA_key_p_value")
        self.RSA_act_execbutton = QtWidgets.QPushButton(self.RSA)
        self.RSA_act_execbutton.setGeometry(QtCore.QRect(520, 310, 151, 33))
        self.RSA_act_execbutton.setObjectName("RSA_act_execbutton")
        self.RSA_key_savebutton = QtWidgets.QPushButton(self.RSA)
        self.RSA_key_savebutton.setGeometry(QtCore.QRect(40, 340, 151, 33))
        self.RSA_key_savebutton.setObjectName("RSA_key_savebutton")
        self.RSA_output_text = QtWidgets.QTextEdit(self.RSA)
        self.RSA_output_text.setGeometry(QtCore.QRect(520, 380, 511, 111))
        self.RSA_output_text.setObjectName("RSA_output_text")
        self.RSA_key_filebutton = QtWidgets.QPushButton(self.RSA)
        self.RSA_key_filebutton.setGeometry(QtCore.QRect(40, 300, 151, 33))
        self.RSA_key_filebutton.setObjectName("RSA_key_filebutton")
        self.RSA_key_x_label = QtWidgets.QLabel(self.RSA)
        self.RSA_key_x_label.setGeometry(QtCore.QRect(50, 140, 16, 17))
        self.RSA_key_x_label.setObjectName("RSA_key_x_label")
        self.RSA_sess_x_value = QtWidgets.QLineEdit(self.RSA)
        self.RSA_sess_x_value.setGeometry(QtCore.QRect(240, 140, 113, 31))
        self.RSA_sess_x_value.setObjectName("RSA_sess_x_value")
        self.RSA_act_label = QtWidgets.QLabel(self.RSA)
        self.RSA_act_label.setGeometry(QtCore.QRect(520, 220, 181, 17))
        self.RSA_act_label.setObjectName("RSA_act_label")
        self.RSA_output_label = QtWidgets.QLabel(self.RSA)
        self.RSA_output_label.setGeometry(QtCore.QRect(520, 360, 231, 17))
        self.RSA_output_label.setObjectName("RSA_output_label")
        self.RSA_key_p_label = QtWidgets.QLabel(self.RSA)
        self.RSA_key_p_label.setGeometry(QtCore.QRect(50, 100, 16, 17))
        self.RSA_key_p_label.setObjectName("RSA_key_p_label")
        self.RSA_sess_g_value = QtWidgets.QLineEdit(self.RSA)
        self.RSA_sess_g_value.setGeometry(QtCore.QRect(240, 180, 113, 31))
        self.RSA_sess_g_value.setObjectName("RSA_sess_g_value")
        self.RSA_sess_g_label = QtWidgets.QLabel(self.RSA)
        self.RSA_sess_g_label.setGeometry(QtCore.QRect(220, 180, 16, 17))
        self.RSA_sess_g_label.setObjectName("RSA_sess_g_label")
        self.RSA_key_genbutton = QtWidgets.QPushButton(self.RSA)
        self.RSA_key_genbutton.setGeometry(QtCore.QRect(40, 262, 151, 31))
        self.RSA_key_genbutton.setObjectName("RSA_key_genbutton")
        self.RSA_key_x_value = QtWidgets.QLineEdit(self.RSA)
        self.RSA_key_x_value.setGeometry(QtCore.QRect(70, 140, 113, 31))
        self.RSA_key_x_value.setObjectName("RSA_key_x_value")
        self.RSA_act_decbutton = QtWidgets.QRadioButton(self.RSA)
        self.RSA_act_decbutton.setGeometry(QtCore.QRect(520, 280, 115, 21))
        self.RSA_act_decbutton.setObjectName("RSA_act_decbutton")
        self.RSA_input_label = QtWidgets.QLabel(self.RSA)
        self.RSA_input_label.setGeometry(QtCore.QRect(520, 70, 231, 17))
        self.RSA_input_label.setObjectName("RSA_input_label")
        self.stackedWidget.addWidget(self.RSA)
        self.ELGAMAL = QtWidgets.QWidget()
        self.ELGAMAL.setObjectName("ELGAMAL")
        self.EG_key_savebutton = QtWidgets.QPushButton(self.ELGAMAL)
        self.EG_key_savebutton.setGeometry(QtCore.QRect(30, 340, 151, 33))
        self.EG_key_savebutton.setObjectName("EG_key_savebutton")
        self.EG_act_execbutton = QtWidgets.QPushButton(self.ELGAMAL)
        self.EG_act_execbutton.setGeometry(QtCore.QRect(510, 310, 151, 33))
        self.EG_act_execbutton.setObjectName("EG_act_execbutton")
        self.EG_key_genbutton = QtWidgets.QPushButton(self.ELGAMAL)
        self.EG_key_genbutton.setGeometry(QtCore.QRect(30, 262, 151, 31))
        self.EG_key_genbutton.setObjectName("EG_key_genbutton")
        self.EG_key_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_key_label.setGeometry(QtCore.QRect(40, 60, 151, 17))
        self.EG_key_label.setObjectName("EG_key_label")
        self.EG_key_filebutton = QtWidgets.QPushButton(self.ELGAMAL)
        self.EG_key_filebutton.setGeometry(QtCore.QRect(30, 300, 151, 33))
        self.EG_key_filebutton.setObjectName("EG_key_filebutton")
        self.EG_input_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_input_label.setGeometry(QtCore.QRect(510, 70, 231, 17))
        self.EG_input_label.setObjectName("EG_input_label")
        self.EG_act_decbutton = QtWidgets.QRadioButton(self.ELGAMAL)
        self.EG_act_decbutton.setGeometry(QtCore.QRect(510, 280, 115, 21))
        self.EG_act_decbutton.setObjectName("EG_act_decbutton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.EG_act_decbutton)
        self.EG_act_encbutton = QtWidgets.QRadioButton(self.ELGAMAL)
        self.EG_act_encbutton.setGeometry(QtCore.QRect(510, 250, 115, 21))
        self.EG_act_encbutton.setObjectName("EG_act_encbutton")
        self.buttonGroup.addButton(self.EG_act_encbutton)
        self.EG_input_filebutton = QtWidgets.QPushButton(self.ELGAMAL)
        self.EG_input_filebutton.setGeometry(QtCore.QRect(870, 210, 151, 33))
        self.EG_input_filebutton.setObjectName("EG_input_filebutton")
        self.EG_output_text = QtWidgets.QTextEdit(self.ELGAMAL)
        self.EG_output_text.setGeometry(QtCore.QRect(510, 380, 511, 111))
        self.EG_output_text.setObjectName("EG_output_text")
        self.EG_act_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_act_label.setGeometry(QtCore.QRect(510, 220, 181, 17))
        self.EG_act_label.setObjectName("EG_act_label")
        self.EG_input_text = QtWidgets.QTextEdit(self.ELGAMAL)
        self.EG_input_text.setGeometry(QtCore.QRect(510, 90, 511, 111))
        self.EG_input_text.setObjectName("EG_input_text")
        self.EG_output_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_output_label.setGeometry(QtCore.QRect(510, 360, 231, 17))
        self.EG_output_label.setObjectName("EG_output_label")
        self.EG_title = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_title.setGeometry(QtCore.QRect(500, 20, 67, 17))
        self.EG_title.setObjectName("EG_title")
        self.EG_returnbutton = QtWidgets.QPushButton(self.ELGAMAL)
        self.EG_returnbutton.setGeometry(QtCore.QRect(490, 530, 97, 33))
        self.EG_returnbutton.setObjectName("EG_returnbutton")
        self.EG_key_p_value = QtWidgets.QLineEdit(self.ELGAMAL)
        self.EG_key_p_value.setGeometry(QtCore.QRect(60, 100, 113, 31))
        self.EG_key_p_value.setObjectName("EG_key_p_value")
        self.EG_key_p_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_key_p_label.setGeometry(QtCore.QRect(40, 100, 16, 17))
        self.EG_key_p_label.setObjectName("EG_key_p_label")
        self.EG_key_x_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_key_x_label.setGeometry(QtCore.QRect(40, 140, 16, 17))
        self.EG_key_x_label.setObjectName("EG_key_x_label")
        self.EG_key_x_value = QtWidgets.QLineEdit(self.ELGAMAL)
        self.EG_key_x_value.setGeometry(QtCore.QRect(60, 140, 113, 31))
        self.EG_key_x_value.setObjectName("EG_key_x_value")
        self.EG_key_g_value = QtWidgets.QLineEdit(self.ELGAMAL)
        self.EG_key_g_value.setGeometry(QtCore.QRect(60, 180, 113, 31))
        self.EG_key_g_value.setObjectName("EG_key_g_value")
        self.EG_key_g_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_key_g_label.setGeometry(QtCore.QRect(40, 180, 16, 17))
        self.EG_key_g_label.setObjectName("EG_key_g_label")
        self.EG_key_y_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_key_y_label.setGeometry(QtCore.QRect(40, 220, 16, 17))
        self.EG_key_y_label.setObjectName("EG_key_y_label")
        self.EG_key_y_value = QtWidgets.QLineEdit(self.ELGAMAL)
        self.EG_key_y_value.setGeometry(QtCore.QRect(60, 220, 113, 31))
        self.EG_key_y_value.setObjectName("EG_key_y_value")
        self.EG_sess_n_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_sess_n_label.setGeometry(QtCore.QRect(210, 100, 16, 17))
        self.EG_sess_n_label.setObjectName("EG_sess_n_label")
        self.EG_sess_g_value = QtWidgets.QLineEdit(self.ELGAMAL)
        self.EG_sess_g_value.setGeometry(QtCore.QRect(230, 180, 113, 31))
        self.EG_sess_g_value.setObjectName("EG_sess_g_value")
        self.EG_sess_x_value = QtWidgets.QLineEdit(self.ELGAMAL)
        self.EG_sess_x_value.setGeometry(QtCore.QRect(230, 140, 113, 31))
        self.EG_sess_x_value.setObjectName("EG_sess_x_value")
        self.EG_sess_n_value = QtWidgets.QLineEdit(self.ELGAMAL)
        self.EG_sess_n_value.setGeometry(QtCore.QRect(230, 100, 113, 31))
        self.EG_sess_n_value.setObjectName("EG_sess_n_value")
        self.EG_sess_g_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_sess_g_label.setGeometry(QtCore.QRect(210, 180, 16, 17))
        self.EG_sess_g_label.setObjectName("EG_sess_g_label")
        self.EG_sess_x_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_sess_x_label.setGeometry(QtCore.QRect(210, 140, 16, 17))
        self.EG_sess_x_label.setObjectName("EG_sess_x_label")
        self.EG_sess_y_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_sess_y_label.setGeometry(QtCore.QRect(210, 220, 16, 17))
        self.EG_sess_y_label.setObjectName("EG_sess_y_label")
        self.EG_sess_y_value = QtWidgets.QLineEdit(self.ELGAMAL)
        self.EG_sess_y_value.setGeometry(QtCore.QRect(230, 220, 113, 31))
        self.EG_sess_y_value.setObjectName("EG_sess_y_value")
        self.EG_sess_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_sess_label.setGeometry(QtCore.QRect(210, 60, 151, 17))
        self.EG_sess_label.setObjectName("EG_sess_label")
        self.EG_sess_genbutton = QtWidgets.QPushButton(self.ELGAMAL)
        self.EG_sess_genbutton.setGeometry(QtCore.QRect(210, 260, 151, 31))
        self.EG_sess_genbutton.setObjectName("EG_sess_genbutton")
        self.EG_fmt_filebutton = QtWidgets.QRadioButton(self.ELGAMAL)
        self.EG_fmt_filebutton.setGeometry(QtCore.QRect(680, 280, 115, 21))
        self.EG_fmt_filebutton.setObjectName("EG_fmt_filebutton")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.EG_fmt_filebutton)
        self.EG_fmt_txtbutton = QtWidgets.QRadioButton(self.ELGAMAL)
        self.EG_fmt_txtbutton.setGeometry(QtCore.QRect(680, 250, 115, 21))
        self.EG_fmt_txtbutton.setObjectName("EG_fmt_txtbutton")
        self.buttonGroup_2.addButton(self.EG_fmt_txtbutton)
        self.EG_fmt_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_fmt_label.setGeometry(QtCore.QRect(680, 220, 181, 17))
        self.EG_fmt_label.setObjectName("EG_fmt_label")
        self.stackedWidget.addWidget(self.ELGAMAL)
        MainWindow.setCentralWidget(self.main)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.connect_buttons()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "TUGAS KRIPTO"))
        self.rsabutton.setText(_translate("MainWindow", "RSA"))
        self.egbutton.setText(_translate("MainWindow", "ELGAMAL"))
        self.RSA_title.setText(_translate("MainWindow", "RSA"))
        self.RSA_returnbutton.setText(_translate("MainWindow", "RETURN"))
        self.RSA_sess_y_label.setText(_translate("MainWindow", "y"))
        self.RSA_sess_genbutton.setText(_translate("MainWindow", "Bangkitkan Kunci"))
        self.RSA_sess_label.setText(_translate("MainWindow", "Kunci Sesi Anda"))
        self.RSA_act_encbutton.setText(_translate("MainWindow", "Enkripsi"))
        self.RSA_sess_x_label.setText(_translate("MainWindow", "x"))
        self.RSA_key_g_label.setText(_translate("MainWindow", "g"))
        self.RSA_sess_n_label.setText(_translate("MainWindow", "n"))
        self.RSA_input_filebutton.setText(_translate("MainWindow", "Pilih dari file"))
        self.RSA_key_y_label.setText(_translate("MainWindow", "y"))
        self.RSA_key_label.setText(_translate("MainWindow", "Kunci Kripto Anda"))
        self.RSA_act_execbutton.setText(_translate("MainWindow", "EXECUTE"))
        self.RSA_key_savebutton.setText(_translate("MainWindow", "Simpan Kunci"))
        self.RSA_key_filebutton.setText(_translate("MainWindow", "Pilih kunci dari file"))
        self.RSA_key_x_label.setText(_translate("MainWindow", "x"))
        self.RSA_act_label.setText(_translate("MainWindow", "Pilih aksi"))
        self.RSA_output_label.setText(_translate("MainWindow", "Hasil"))
        self.RSA_key_p_label.setText(_translate("MainWindow", "p"))
        self.RSA_sess_g_label.setText(_translate("MainWindow", "g"))
        self.RSA_key_genbutton.setText(_translate("MainWindow", "Bangkitkan Kunci"))
        self.RSA_act_decbutton.setText(_translate("MainWindow", "Dekripsi"))
        self.RSA_input_label.setText(_translate("MainWindow", "Masukan teks Anda disini"))
        self.EG_key_savebutton.setText(_translate("MainWindow", "Simpan Kunci"))
        self.EG_act_execbutton.setText(_translate("MainWindow", "EXECUTE"))
        self.EG_key_genbutton.setText(_translate("MainWindow", "Bangkitkan Kunci"))
        self.EG_key_label.setText(_translate("MainWindow", "Kunci Kripto Anda"))
        self.EG_key_filebutton.setText(_translate("MainWindow", "Pilih kunci dari file"))
        self.EG_input_label.setText(_translate("MainWindow", "Masukan teks Anda disini"))
        self.EG_act_decbutton.setText(_translate("MainWindow", "Dekripsi"))
        self.EG_act_encbutton.setText(_translate("MainWindow", "Enkripsi"))
        self.EG_input_filebutton.setText(_translate("MainWindow", "Pilih dari file"))
        self.EG_act_label.setText(_translate("MainWindow", "Pilih aksi"))
        self.EG_output_label.setText(_translate("MainWindow", "Hasil"))
        self.EG_title.setText(_translate("MainWindow", "ELGAMAL"))
        self.EG_returnbutton.setText(_translate("MainWindow", "RETURN"))
        self.EG_key_p_label.setText(_translate("MainWindow", "p"))
        self.EG_key_x_label.setText(_translate("MainWindow", "x"))
        self.EG_key_g_label.setText(_translate("MainWindow", "g"))
        self.EG_key_y_label.setText(_translate("MainWindow", "y"))
        self.EG_sess_n_label.setText(_translate("MainWindow", "n"))
        self.EG_sess_g_label.setText(_translate("MainWindow", "g"))
        self.EG_sess_x_label.setText(_translate("MainWindow", "x"))
        self.EG_sess_y_label.setText(_translate("MainWindow", "y"))
        self.EG_sess_label.setText(_translate("MainWindow", "Kunci Sesi Anda"))
        self.EG_sess_genbutton.setText(_translate("MainWindow", "Bangkitkan Kunci"))
        self.EG_fmt_filebutton.setText(_translate("MainWindow", "Berkas"))
        self.EG_fmt_txtbutton.setText(_translate("MainWindow", "Teks"))
        self.EG_fmt_label.setText(_translate("MainWindow", "Pilih format"))

    def connect_buttons(self):
        self.rsabutton.clicked.connect(lambda:self.stackedWidget.setCurrentIndex(1))
        self.egbutton.clicked.connect(lambda:self.stackedWidget.setCurrentIndex(2))
        # self.egbutton.clicked.connect(self.toEGPage())
        # self.RSA_act_decbutton.setText(_translate("MainWindow", "Dekripsi"))
        # self.RSA_key_savebutton.setText(_translate("MainWindow", "Simpan Kunci"))
        # self.RSA_key_filebutton.setText(_translate("MainWindow", "Pilih kunci dari file"))
        # self.RSA_act_execbutton.setText(_translate("MainWindow", "EXECUTE"))
        # self.RSA_key_genbutton.setText(_translate("MainWindow", "Bangkitkan Kunci"))
        # self.RSA_input_filebutton.setText(_translate("MainWindow", "Pilih dari file"))
        # self.RSA_act_encbutton.setText(_translate("MainWindow", "Enkripsi"))
        # self.EG_key_savebutton.setText(_translate("MainWindow", "Simpan Kunci"))
        # self.EG_act_execbutton.setText(_translate("MainWindow", "EXECUTE"))
        # self.EG_key_genbutton.setText(_translate("MainWindow", "Bangkitkan Kunci"))
        # self.EG_key_filebutton.setText(_translate("MainWindow", "Pilih kunci dari file"))
        # self.EG_act_decbutton.setText(_translate("MainWindow", "Dekripsi"))
        # self.EG_act_encbutton.setText(_translate("MainWindow", "Enkripsi"))
        # self.EG_input_filebutton.setText(_translate("MainWindow", "Pilih dari file"))
        self.RSA_returnbutton.clicked.connect(lambda:self.stackedWidget.setCurrentIndex(0))
        self.EG_returnbutton.clicked.connect(lambda:self.stackedWidget.setCurrentIndex(0))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
