# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.main = QtWidgets.QWidget(MainWindow)
        self.main.setObjectName("main")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main)
        self.stackedWidget.setGeometry(QtCore.QRect(-10, 0, 801, 601))
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainpage = QtWidgets.QWidget()
        self.mainpage.setObjectName("mainpage")
        self.title = QtWidgets.QLabel(self.mainpage)
        self.title.setGeometry(QtCore.QRect(340, 120, 111, 20))
        self.title.setObjectName("title")
        self.rsabutton = QtWidgets.QPushButton(self.mainpage)
        self.rsabutton.setGeometry(QtCore.QRect(340, 170, 97, 33))
        self.rsabutton.setObjectName("rsabutton")
        self.egbutton = QtWidgets.QPushButton(self.mainpage)
        self.egbutton.setGeometry(QtCore.QRect(340, 220, 97, 33))
        self.egbutton.setObjectName("egbutton")
        self.stackedWidget.addWidget(self.mainpage)
        self.RSA = QtWidgets.QWidget()
        self.RSA.setObjectName("RSA")
        self.RSA_act_label = QtWidgets.QLabel(self.RSA)
        self.RSA_act_label.setGeometry(QtCore.QRect(40, 320, 181, 17))
        self.RSA_act_label.setObjectName("RSA_act_label")
        self.RSA_key_label = QtWidgets.QLabel(self.RSA)
        self.RSA_key_label.setGeometry(QtCore.QRect(40, 60, 151, 17))
        self.RSA_key_label.setObjectName("RSA_key_label")
        self.RSA_act_decbutton = QtWidgets.QRadioButton(self.RSA)
        self.RSA_act_decbutton.setGeometry(QtCore.QRect(40, 380, 115, 21))
        self.RSA_act_decbutton.setObjectName("RSA_act_decbutton")
        self.RSA_key_savebutton = QtWidgets.QPushButton(self.RSA)
        self.RSA_key_savebutton.setGeometry(QtCore.QRect(40, 250, 151, 33))
        self.RSA_key_savebutton.setObjectName("RSA_key_savebutton")
        self.RSA_output_label = QtWidgets.QLabel(self.RSA)
        self.RSA_output_label.setGeometry(QtCore.QRect(240, 290, 231, 17))
        self.RSA_output_label.setObjectName("RSA_output_label")
        self.RSA_key_filebutton = QtWidgets.QPushButton(self.RSA)
        self.RSA_key_filebutton.setGeometry(QtCore.QRect(40, 210, 151, 33))
        self.RSA_key_filebutton.setObjectName("RSA_key_filebutton")
        self.RSA_input_label = QtWidgets.QLabel(self.RSA)
        self.RSA_input_label.setGeometry(QtCore.QRect(240, 60, 231, 17))
        self.RSA_input_label.setObjectName("RSA_input_label")
        self.RSA_output_text = QtWidgets.QTextEdit(self.RSA)
        self.RSA_output_text.setGeometry(QtCore.QRect(240, 310, 511, 201))
        self.RSA_output_text.setObjectName("RSA_output_text")
        self.RSA_input_text = QtWidgets.QTextEdit(self.RSA)
        self.RSA_input_text.setGeometry(QtCore.QRect(240, 80, 511, 201))
        self.RSA_input_text.setObjectName("RSA_input_text")
        self.RSA_act_execbutton = QtWidgets.QPushButton(self.RSA)
        self.RSA_act_execbutton.setGeometry(QtCore.QRect(40, 450, 151, 33))
        self.RSA_act_execbutton.setObjectName("RSA_act_execbutton")
        self.RSA_key_genbutton = QtWidgets.QPushButton(self.RSA)
        self.RSA_key_genbutton.setGeometry(QtCore.QRect(40, 170, 151, 33))
        self.RSA_key_genbutton.setObjectName("RSA_key_genbutton")
        self.RSA_input_filebutton = QtWidgets.QPushButton(self.RSA)
        self.RSA_input_filebutton.setGeometry(QtCore.QRect(40, 410, 151, 33))
        self.RSA_input_filebutton.setObjectName("RSA_input_filebutton")
        self.RSA_act_encbutton = QtWidgets.QRadioButton(self.RSA)
        self.RSA_act_encbutton.setGeometry(QtCore.QRect(40, 350, 115, 21))
        self.RSA_act_encbutton.setObjectName("RSA_act_encbutton")
        self.RSA_title = QtWidgets.QLabel(self.RSA)
        self.RSA_title.setGeometry(QtCore.QRect(380, 20, 67, 17))
        self.RSA_title.setObjectName("RSA_title")
        self.RSA_returnbutton = QtWidgets.QPushButton(self.RSA)
        self.RSA_returnbutton.setGeometry(QtCore.QRect(370, 540, 97, 33))
        self.RSA_returnbutton.setObjectName("RSA_returnbutton")
        self.stackedWidget.addWidget(self.RSA)
        self.ELGAMAL = QtWidgets.QWidget()
        self.ELGAMAL.setObjectName("ELGAMAL")
        self.EG_key_savebutton = QtWidgets.QPushButton(self.ELGAMAL)
        self.EG_key_savebutton.setGeometry(QtCore.QRect(40, 250, 151, 33))
        self.EG_key_savebutton.setObjectName("EG_key_savebutton")
        self.EG_act_execbutton = QtWidgets.QPushButton(self.ELGAMAL)
        self.EG_act_execbutton.setGeometry(QtCore.QRect(40, 450, 151, 33))
        self.EG_act_execbutton.setObjectName("EG_act_execbutton")
        self.EG_key_genbutton = QtWidgets.QPushButton(self.ELGAMAL)
        self.EG_key_genbutton.setGeometry(QtCore.QRect(40, 170, 151, 33))
        self.EG_key_genbutton.setObjectName("EG_key_genbutton")
        self.EG_key_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_key_label.setGeometry(QtCore.QRect(40, 60, 151, 17))
        self.EG_key_label.setObjectName("EG_key_label")
        self.EG_key_filebutton = QtWidgets.QPushButton(self.ELGAMAL)
        self.EG_key_filebutton.setGeometry(QtCore.QRect(40, 210, 151, 33))
        self.EG_key_filebutton.setObjectName("EG_key_filebutton")
        self.EG_input_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_input_label.setGeometry(QtCore.QRect(240, 60, 231, 17))
        self.EG_input_label.setObjectName("EG_input_label")
        self.EG_act_decbutton = QtWidgets.QRadioButton(self.ELGAMAL)
        self.EG_act_decbutton.setGeometry(QtCore.QRect(40, 380, 115, 21))
        self.EG_act_decbutton.setObjectName("EG_act_decbutton")
        self.EG_act_encbutton = QtWidgets.QRadioButton(self.ELGAMAL)
        self.EG_act_encbutton.setGeometry(QtCore.QRect(40, 350, 115, 21))
        self.EG_act_encbutton.setObjectName("EG_act_encbutton")
        self.EG_input_filebutton = QtWidgets.QPushButton(self.ELGAMAL)
        self.EG_input_filebutton.setGeometry(QtCore.QRect(40, 410, 151, 33))
        self.EG_input_filebutton.setObjectName("EG_input_filebutton")
        self.EG_output_text = QtWidgets.QTextEdit(self.ELGAMAL)
        self.EG_output_text.setGeometry(QtCore.QRect(240, 310, 511, 201))
        self.EG_output_text.setObjectName("EG_output_text")
        self.EG_act_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_act_label.setGeometry(QtCore.QRect(40, 320, 181, 17))
        self.EG_act_label.setObjectName("EG_act_label")
        self.EG_input_text = QtWidgets.QTextEdit(self.ELGAMAL)
        self.EG_input_text.setGeometry(QtCore.QRect(240, 80, 511, 201))
        self.EG_input_text.setObjectName("EG_input_text")
        self.EG_output_label = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_output_label.setGeometry(QtCore.QRect(240, 290, 231, 17))
        self.EG_output_label.setObjectName("EG_output_label")
        self.EG_title = QtWidgets.QLabel(self.ELGAMAL)
        self.EG_title.setGeometry(QtCore.QRect(380, 20, 67, 17))
        self.EG_title.setObjectName("EG_title")
        self.EG_returnbutton = QtWidgets.QPushButton(self.ELGAMAL)
        self.EG_returnbutton.setGeometry(QtCore.QRect(370, 530, 97, 33))
        self.EG_returnbutton.setObjectName("EG_returnbutton")
        self.stackedWidget.addWidget(self.ELGAMAL)
        MainWindow.setCentralWidget(self.main)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.connect_buttons()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "TUGAS KRIPTO"))
        self.rsabutton.setText(_translate("MainWindow", "RSA"))
        self.egbutton.setText(_translate("MainWindow", "ELGAMAL"))
        self.RSA_act_label.setText(_translate("MainWindow", "Pilih aksi"))
        self.RSA_key_label.setText(_translate("MainWindow", "Kunci Anda"))
        self.RSA_act_decbutton.setText(_translate("MainWindow", "Dekripsi"))
        self.RSA_key_savebutton.setText(_translate("MainWindow", "Simpan Kunci"))
        self.RSA_output_label.setText(_translate("MainWindow", "Hasil"))
        self.RSA_key_filebutton.setText(_translate("MainWindow", "Pilih kunci dari file"))
        self.RSA_input_label.setText(_translate("MainWindow", "Masukan teks Anda disini"))
        self.RSA_act_execbutton.setText(_translate("MainWindow", "EXECUTE"))
        self.RSA_key_genbutton.setText(_translate("MainWindow", "Bangkitkan Kunci"))
        self.RSA_input_filebutton.setText(_translate("MainWindow", "Pilih dari file"))
        self.RSA_act_encbutton.setText(_translate("MainWindow", "Enkripsi"))
        self.RSA_title.setText(_translate("MainWindow", "RSA"))
        self.RSA_returnbutton.setText(_translate("MainWindow", "RETURN"))
        self.EG_key_savebutton.setText(_translate("MainWindow", "Simpan Kunci"))
        self.EG_act_execbutton.setText(_translate("MainWindow", "EXECUTE"))
        self.EG_key_genbutton.setText(_translate("MainWindow", "Bangkitkan Kunci"))
        self.EG_key_label.setText(_translate("MainWindow", "Kunci Anda"))
        self.EG_key_filebutton.setText(_translate("MainWindow", "Pilih kunci dari file"))
        self.EG_input_label.setText(_translate("MainWindow", "Masukan teks Anda disini"))
        self.EG_act_decbutton.setText(_translate("MainWindow", "Dekripsi"))
        self.EG_act_encbutton.setText(_translate("MainWindow", "Enkripsi"))
        self.EG_input_filebutton.setText(_translate("MainWindow", "Pilih dari file"))
        self.EG_act_label.setText(_translate("MainWindow", "Pilih aksi"))
        self.EG_output_label.setText(_translate("MainWindow", "Hasil"))
        self.EG_title.setText(_translate("MainWindow", "ELGAMAL"))
        self.EG_returnbutton.setText(_translate("MainWindow", "RETURN"))
    
    def connect_buttons(self):
        self.rsabutton.clicked.connect(lambda:self.stackedWidget.setCurrentIndex(1))
        self.egbutton.clicked.connect(lambda:self.stackedWidget.setCurrentIndex(2))
        # self.egbutton.clicked.connect(self.toEGPage())
        # self.RSA_act_decbutton.setText(_translate("MainWindow", "Dekripsi"))
        # self.RSA_key_savebutton.setText(_translate("MainWindow", "Simpan Kunci"))
        # self.RSA_key_filebutton.setText(_translate("MainWindow", "Pilih kunci dari file"))
        # self.RSA_act_execbutton.setText(_translate("MainWindow", "EXECUTE"))
        # self.RSA_key_genbutton.setText(_translate("MainWindow", "Bangkitkan Kunci"))
        # self.RSA_input_filebutton.setText(_translate("MainWindow", "Pilih dari file"))
        # self.RSA_act_encbutton.setText(_translate("MainWindow", "Enkripsi"))
        # self.EG_key_savebutton.setText(_translate("MainWindow", "Simpan Kunci"))
        # self.EG_act_execbutton.setText(_translate("MainWindow", "EXECUTE"))
        # self.EG_key_genbutton.setText(_translate("MainWindow", "Bangkitkan Kunci"))
        # self.EG_key_filebutton.setText(_translate("MainWindow", "Pilih kunci dari file"))
        # self.EG_act_decbutton.setText(_translate("MainWindow", "Dekripsi"))
        # self.EG_act_encbutton.setText(_translate("MainWindow", "Enkripsi"))
        # self.EG_input_filebutton.setText(_translate("MainWindow", "Pilih dari file"))
        self.RSA_returnbutton.clicked.connect(lambda:self.stackedWidget.setCurrentIndex(0))
        self.EG_returnbutton.clicked.connect(lambda:self.stackedWidget.setCurrentIndex(0))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
